# (1) 클러스터의 중심점을 몇 회만에 찾는지, 매 반복 중심값만을 출력한다.

# (2) 배정된 클러스터가 맞는지 비교하여 동일한지 확인하세요.


In [1]:
def normDist(x1, x2):
    #dist=np.sqrt(sum(np.power(x1 - x2, 2))) #36.406001444695193
    dist = np.linalg.norm(x1 - x2) #36.406001444695193
    return dist

In [2]:
def cluster(x, k, centroids):
    row, col = x.shape
    clusterAssigned = np.zeros(shape=(row, 2), dtype=float)
    # print (clusterAssigned)
    clusterUpdated=True
    iter = 1
    print ("매 반복 중심값을 출력합니다.")
    while(clusterUpdated):
        print ("\n\n====== Iteration {} ======".format(iter))
        # STEP 1: assign to closer cluster
        for i in range(row):
            minDist = np.inf   # set arbitray max to minDist
            minIndex = -1      # set arbitray index to minIndex
            # compute distance and assign to closer cluster
            for j in range(k):
                # distance from centroids[j] to x[0]
                distJI = normDist(centroids[j], x[i])
                # print ("Distance {:.3f} between {} and {}".format(distJI, centroids[j], x[i]))
                # pick the closest centroid
                if distJI < minDist:
                    minDist = distJI
                    minIndex = j
            #print (".....Assigning {} to {}th centroid by {:.3f}".format(x[i], minIndex, minDist))
            clusterAssigned[i] = [minIndex, minDist]   #-----changed
        #print ("\n.....Assigned clusters: \n {}".format(clusterAssigned))
        # STEP 2: update centroids
        _centroids=np.zeros(shape = (k, x.shape[1]), dtype=float)
        for cent in range(k):
            # read data by index and average them
            _centroids[cent] = np.mean(x[clusterAssigned[:,0]==cent],axis=0)
        # print ("Centroids updated: \n", _centroids)
        # STEP 3: see if centroids is updated. STOP if NOT updated
        comparison = np.isclose(centroids, _centroids) 
        #np.isclose()  in case some tolerence is required
        if(comparison.all() == True):
            print ("\n.....NOT Updating Centroids\n {} => \n{} \n".format(centroids, _centroids))
            print("클러스터의 중심값을 {} 회만에 찾았습니다.\n".format(iter))
            clusterUpdated = False
            return centroids, clusterAssigned
        else:
            print ("\n.....Updating Centroids\n {} => \n{}".format(centroids, _centroids))
            centroids = _centroids
            iter += 1

In [3]:
import numpy as np
from sklearn.datasets import make_blobs
k = 4
X, y = make_blobs(n_samples=100, centers=4, cluster_std=0.60, random_state=0) 

centroids = np.empty((0,2), float) # 초기 중심값 설정
for i in range(0, len(X), int(len(X)/4.0)):
    centroids = np.append(centroids, [list(X[i])], axis=0)

centroids, clusterAssigned = cluster(X, k, centroids)

dic = {0:1, 1:2, 2:3, 3:0}  # 분류는 잘 됐지만 index가 다른 문제를 처리합니다.
clusterAssignedIndex = clusterAssigned[:,0]
for count, i in enumerate(clusterAssignedIndex):
    clusterAssignedIndex[count] = dic[i]
    
print("배정된 클러스터가 맞는지 비교하여 동일한지 확인합니다.")
print("\n분류 클러스터 : \n", clusterAssignedIndex.astype(int))
print("\n배정된 클러스터 : \n",y)
print("\n비교 : \n", clusterAssignedIndex == y)

매 반복 중심값을 출력합니다.


====== Iteration 1 ======

.....Updating Centroids
 [[ 0.669787    3.59540802]
 [-1.58597553  2.51979529]
 [ 0.22459286  4.77028154]
 [ 1.4949318   3.85848832]] => 
[[ 1.00509097  2.04243306]
 [-1.63043905  3.09879034]
 [-0.82440658  6.94334192]
 [ 1.98421483  2.51124864]]


====== Iteration 2 ======

.....Updating Centroids
 [[ 1.00509097  2.04243306]
 [-1.63043905  3.09879034]
 [-0.82440658  6.94334192]
 [ 1.98421483  2.51124864]] => 
[[ 1.46428066  1.28068515]
 [-1.31624236  3.29763171]
 [-1.09151585  7.46989518]
 [ 1.72629501  3.10855982]]


====== Iteration 3 ======

.....Updating Centroids
 [[ 1.46428066  1.28068515]
 [-1.31624236  3.29763171]
 [-1.09151585  7.46989518]
 [ 1.72629501  3.10855982]] => 
[[ 1.9388131   0.93520024]
 [-1.3238994   3.30600145]
 [-1.22498973  7.6619397 ]
 [ 1.19140427  4.14283465]]


====== Iteration 4 ======

.....Updating Centroids
 [[ 1.9388131   0.93520024]
 [-1.3238994   3.30600145]
 [-1.22498973  7.6619397 ]
 [ 1.19140427  4.142